-- Insert sample ads data
INSERT INTO public.ads (title, content, detailed_info, ad_type, position, target_url, banner_image, banner_url, show_popup, is_active, priority, created_by) VALUES
('RevEmpire ChatBox', 'Connect with players worldwide! 14 multiplayer games and real-time chat - all free!', 'Experience the ultimate gaming community with RevEmpire ChatBox! Join thousands of players in real-time multiplayer action. Our platform features 14 different games including strategy games like Chess and Checkers, puzzle games like Memory and Number Puzzle, action games like Battleship, and party games like Would Rather and Trivia. Chat with players from around the world while you play!', 'banner', 'top', 'https://revempire.com', 'https://via.placeholder.com/468x60/2563eb/ffffff?text=Join+RevEmpire+Now', 'https://revempire.com/register', true, true, 1, '00000000-0000-0000-0000-000000000000'),

('New Game Alert!', 'Try our latest multiplayer puzzle games - Challenge your friends now!', 'Discover our newest additions to the game collection! Challenge your mind with advanced puzzle mechanics, compete in real-time with friends, and climb the global leaderboards. New games are added monthly with enhanced graphics and innovative gameplay features.', 'banner', 'sidebar', 'https://revempire.com/games', 'https://via.placeholder.com/468x60/16a34a/ffffff?text=Play+New+Games', 'https://revempire.com/games/new', true, true, 1, '00000000-0000-0000-0000-000000000000'),

('Join the Tournament', 'Weekly tournaments starting soon. Win prizes and climb the leaderboard!', 'Participate in our weekly tournaments and compete for amazing prizes! Each week features different game categories with cash prizes, premium memberships, and exclusive titles. Tournament brackets are organized by skill level, ensuring fair competition for all players.', 'banner', 'bottom', 'https://revempire.com/tournaments', 'https://via.placeholder.com/468x60/dc2626/ffffff?text=Tournament+Registration', 'https://revempire.com/tournaments/register', true, true, 1, '00000000-0000-0000-0000-000000000000'),

('Play More Games!', 'Discover 14 amazing multiplayer games - Strategy, Action, Puzzle & more!', 'Explore our complete game library featuring 14 unique multiplayer experiences! From classic strategy games to modern puzzle challenges, there is something for every player. All games support real-time multiplayer, chat integration, and achievement systems.', 'banner', 'popup', 'https://revempire.com/games', 'https://via.placeholder.com/468x60/7c3aed/ffffff?text=Explore+All+Games', 'https://revempire.com/games/all', true, true, 1, '00000000-0000-0000-0000-000000000000')

ON CONFLICT (id) DO NOTHING;