// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oysutzfurpgictdgxuzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95c3V0emZ1cnBnaWN0ZGd4dXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzU4MjIsImV4cCI6MjA3MzgxMTgyMn0.n7mC5MaOQOD9UTJuugWnkEq4Nu-EMHOluAXYQnOwrQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});